### ISSUE TITLE
No module named hyppo._utils when importing models

### ISSUE THREAD

**Issue by christospmath** [neurodata/hyppo#190] opened 2021-03-21 13:27 UTC
My issue is when trying to import the DCSBM model:

```
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import hyppo 


from hyppo.time_series import _utils as _utils 
from graspy.embed import AdjacencySpectralEmbed
from graspy.models import DCSBMEstimator 
from graspy.models import EREstimator 
from graspy.models import SBMEstimator

from graspy.models.sbm import _block_to_full, _get_block_indices
from graspy.simulations import er_np, sbm

```

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-33-287386449480> in <module>()
      8 from hyppo.time_series import _utils as _utils
      9 from graspy.embed import AdjacencySpectralEmbed
---> 10 from graspy.models import DCSBMEstimator
     11 from graspy.models import EREstimator
     12 from graspy.models import SBMEstimator

2 frames
/usr/local/lib/python3.7/dist-packages/graspy/inference/latent_distribution_test.py in <module>()
     26 from sklearn.metrics.pairwise import PAIRWISE_KERNEL_FUNCTIONS
     27 from hyppo.ksample import KSample
---> 28 from hyppo._utils import gaussian
     29 
     30 _VALID_DISTANCES = list(PAIRED_DISTANCES.keys())

ModuleNotFoundError: No module named 'hyppo._utils'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
```
I think hyppo._utils doesn't exist and has been replaced by hyppo.time_series and inside that folder there exists the required _utils package required. 

How do we fix this? 

I was just trying to run the tutorial: https://docs.neurodata.io/notebooks/pedigo/graspologic/2020/09/24/latent_model_tutorial.html
#### Version information

- Google colab

**Comment by sampan501** [comment] 2021-03-21 14:00
This is likely because `hyppo` v0.2.0+ adopted a different API to make it more extensible for the future. The error trace mentioned is a known [issue](https://github.com/microsoft/graspologic/issues/659) that the developers for `graspologic` will fix soon. The solution, for the time being, is to use `hyppo` v0.1.3 and you should be able to do that using `!pip` in the notebook.

**Comment by sampan501** [comment] 2021-03-21 14:01
Since this is not a bug within `hyppo`, closing the issue

**Closed as completed by sampan501** 2021-03-21 14:01 UTC
Labels: bug
